# Index regeneration (constitution section 4). Part of the engine (section 9):
# changed only on the repository owner's explicit request.
# Indexes are build products carrying zero original information - this script is their only author.
# Deterministic by law: same tree in, same bytes out (UTF-8 no BOM, LF, ordinal ordering).
#
#   regen.ps1          write mode: rewrite every index.md from the documents
#   regen.ps1 -Check   check mode: regenerate in memory, diff against disk, change nothing
#
# Lint runs first and aborts regen on failure (section 4 rule 4).

[CmdletBinding()]
param([switch]$Check)

. (Join-Path $PSScriptRoot 'common.ps1')

# --- Lint gate ---
$lintOutput = & (Join-Path $PSScriptRoot 'lint.ps1')
if ($LASTEXITCODE -ne 0) {
    $lintOutput | ForEach-Object { Write-Output $_ }
    Write-Output 'REGEN ABORTED: lint must pass first - regen never runs over a nonconformant tree (constitution section 4).'
    exit 1
}

$docsRoot = Get-DocsRoot
$generatedNote = 'Generated by the documentation engine - do not edit by hand.'

function Get-DocLine {
    # "* [Title](file.md) - description" derived purely from frontmatter
    param([System.IO.FileInfo]$Doc, [string]$LinkPrefix)
    $fm = ConvertFrom-Frontmatter ([System.IO.File]::ReadAllLines($Doc.FullName))
    $t = [string]$fm.data['title']
    $d = [string]$fm.data['description']
    return ('* [{0}]({1}{2}) - {3}' -f $t, $LinkPrefix, $Doc.Name, $d)
}

function Get-SortedDocs([string]$DirPath) {
    # Ordinal sort by law (constitution section 4 rule 3): Sort-Object is culture-aware and
    # collates differently on Windows (NLS) vs ubuntu (ICU), so it must never be used here.
    $r = @(Get-ChildItem -LiteralPath $DirPath -File -Filter '*.md' -Force |
        Where-Object { $_.Name -ne 'index.md' })
    [Array]::Sort($r, [System.Comparison[object]] { param($a, $b) [string]::CompareOrdinal($a.Name, $b.Name) })
    return @($r)
}

function Get-SubjectDirs([string]$KindPath) {
    $r = @(Get-ChildItem -LiteralPath $KindPath -Directory -Force |
        Where-Object { $_.Name -ne 'assets' })
    [Array]::Sort($r, [System.Comparison[object]] { param($a, $b) [string]::CompareOrdinal($a.Name, $b.Name) })
    return @($r)
}

# --- Build every index deterministically: path -> content ---
$indexes = [ordered]@{}

# Root index: okf_version frontmatter (section 1) + governance pointer (section 4 rule 5) + the six kinds
$rootLines = @(
    '---'
    'okf_version: "0.2"'
    '---'
    ''
    '# Documentation'
    ''
    ('> Governed by [the documentation constitution](_system/constitution.md). ' + $generatedNote)
    ''
)
foreach ($kind in $Script:KindDirs.Keys) {
    $rootLines += ('* [{0}/]({0}/) - {1}' -f $kind, $Script:KindQuestions[$kind])
}
$indexes[(Join-Path $docsRoot 'index.md')] = ($rootLines -join "`n") + "`n"

# Kind and subject indexes
foreach ($kind in $Script:KindDirs.Keys) {
    $kindPath = Join-Path $docsRoot $kind
    if (-not (Test-Path -LiteralPath $kindPath)) { continue }

    $heading = $kind.Substring(0, 1).ToUpper() + $kind.Substring(1)
    $lines = @(
        ('# {0}' -f $heading)
        ''
        ('> {0} {1}' -f $Script:KindQuestions[$kind], $generatedNote)
        ''
    )
    $entries = @()
    foreach ($doc in (Get-SortedDocs $kindPath)) { $entries += (Get-DocLine $doc '') }
    foreach ($subject in (Get-SubjectDirs $kindPath)) {
        $count = @(Get-SortedDocs $subject.FullName).Count
        $noun = 'documents'; if ($count -eq 1) { $noun = 'document' }
        $entries += ('* [{0}/]({0}/) - {1} {2}' -f $subject.Name, $count, $noun)
    }
    if ($entries.Count -eq 0) { $entries = @('(empty)') }
    $lines += $entries
    $indexes[(Join-Path $kindPath 'index.md')] = ($lines -join "`n") + "`n"

    foreach ($subject in (Get-SubjectDirs $kindPath)) {
        $sLines = @(
            ('# {0}/{1}' -f $kind, $subject.Name)
            ''
            ('> {0}' -f $generatedNote)
            ''
        )
        $sEntries = @()
        foreach ($doc in (Get-SortedDocs $subject.FullName)) { $sEntries += (Get-DocLine $doc '') }
        if ($sEntries.Count -eq 0) { $sEntries = @('(empty)') }
        $sLines += $sEntries
        $indexes[(Join-Path $subject.FullName 'index.md')] = ($sLines -join "`n") + "`n"
    }
}

# --- Apply or verify ---
if ($Check) {
    $drift = New-Object System.Collections.Generic.List[string]
    foreach ($path in $indexes.Keys) {
        $rel = Get-RelativeDocPath $docsRoot $path
        if (-not (Test-Path -LiteralPath $path)) { $drift.Add(('{0}: missing' -f $rel)); continue }
        $bytes = [System.IO.File]::ReadAllBytes($path)
        if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
            $drift.Add(('{0}: has a BOM (regen writes UTF-8 without BOM)' -f $rel)); continue
        }
        $actual = [System.IO.File]::ReadAllText($path)
        if (-not (Compare-NormalizedContent $indexes[$path] $actual)) { $drift.Add(('{0}: stale' -f $rel)) }
    }
    # indexes on disk that regeneration would not produce (e.g. in a dissolved subject folder)
    foreach ($kind in $Script:KindDirs.Keys) {
        $kindPath = Join-Path $docsRoot $kind
        if (-not (Test-Path -LiteralPath $kindPath)) { continue }
        foreach ($onDisk in (Get-ChildItem -LiteralPath $kindPath -Recurse -File -Filter 'index.md')) {
            if (-not $indexes.Contains($onDisk.FullName)) {
                $drift.Add(('{0}: ghost (regeneration would not produce this index)' -f (Get-RelativeDocPath $docsRoot $onDisk.FullName)))
            }
        }
    }
    if ($drift.Count -gt 0) {
        $drift | ForEach-Object { Write-Output $_ }
        Write-Output ('INDEX CHECK FAILED: {0} index file(s) out of sync. Run regen.ps1 and commit the result.' -f $drift.Count)
        exit 1
    }
    Write-Output ('INDEX CHECK OK: {0} index file(s) match regeneration.' -f $indexes.Count)
    exit 0
}
else {
    foreach ($path in $indexes.Keys) {
        Write-Utf8LfFile -Path $path -Content $indexes[$path]
    }
    Write-Output ('REGEN OK: {0} index file(s) written.' -f $indexes.Count)
    exit 0
}
